config/routes.rb
Rails.application.routes.draw do
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete 'logout' => "sessions#destroy"
  root to: "games#index"
  resources :users, :games, :reviews, :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :review
  validates :username, :body, presence: true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :reviews
  validates :name, :developer, :publisher, :genre, :image_url, :audio_url, :platform, :rating, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :game
  has_many :comments, dependent: :destroy
  validates :username, :rating, :body, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: 1..10}
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase}
  validates :username, presence: true, length: {maximum: 50}
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, except: [:create]

  def index
    @comments = Comment.all
  end
  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.review_id = params[:review_id]
    @comment.save
    redirect_to review_path(@comment.review)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update comment_params
    redirect_to @review
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:username, :review_id, :body)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @games = Game.find(params[:id])
  end

  private
  def game_params
    params.require(:game).permit(:name, :developer, :publisher, :genre, :image_url, :audio_url, :platform, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.game_id = params[:game_id]
    @review.save
    redirect_to game_path(@review.game)
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update review_params
    redirect_to @review
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:username, :rating, :body, :game_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid username/password combination"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to new_users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    sesson[:user_id] = user.id
  end

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end

  def logged_in
    !current_user.nil?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_game.html.erb
<div class="games-all">
  <% @games.each do |game| %>
    <p>
      <% game.name %>
    </p>
    <p>
      <img src="<% game.image_url %>"/>
    </p>
  <% end %>
</div>

app/views/games/show.html.erb
<%= render @game %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameReviewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in %>
    <div id="logout">
      <%= button_to 'Logout', logout_path, :method => :delete %>
    </div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user, :html => {:class => "container"} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.error.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <%= f.label :username, "Username: " %>
    <%= f.text_field :username %>
    <%= f.label :email, "Email: " %>
    <%= f.text_field :email %>
    <%= f.label :password, "Password: " %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, "Confirm Password: " %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<div id="user-page">
  <h1>Welcome, <%= @user.username %></h1>
</div>

<%= link_to 'Game List', games_path %>
<%= link_to 'Log Out', logout_path, method: :delete %>